### ISSUE TITLE
Insert prefixes before and not after the official property 

### ISSUE THREAD

**Issue by martin-braun** [stevengeeky/css-auto-prefix#6]
This extension is great, but it produces CSS like this:

```css
#my-element {
	transition: margin 0.3s;
	-webkit-transition: margin 0.3s;
	-moz-transition: margin 0.3s;
	-ms-transition: margin 0.3s;
	-o-transition: margin 0.3s;
}
```

[The W3C property should always come last](https://stackoverflow.com/questions/36225219/what-is-the-proper-way-to-order-vendor-prefixes), so the produced code should look like this, instead:

```css
#my-element {
	-webkit-transition: margin 0.3s;
	-moz-transition: margin 0.3s;
	-ms-transition: margin 0.3s;
	-o-transition: margin 0.3s;
	transition: margin 0.3s;
}
```
